[workspace]
resolver = "2"
members = [
    "apps/osu-radio-cli",
    "apps/osu-radio-gui-vizia",
    "apps/osu-radio-server",
    "crates/osu-radio-client",
    "crates/radio-core",
    "crates/radio-db",
    "crates/radio-scanner",
]

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
anyhow = { version = "1.0.100" }
dotenvy = { version = "0.15.7" }
tokio = { version = "1.52.3", features = ["full"] }

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
redundant_pub_crate = "allow"
# DENY PANICS:
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
