[package]
name = "osu-radio-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["sqlite"]
sqlite = ["radio-db/sqlite"]
postgres = ["radio-db/postgres"]

[dependencies]
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
dotenvy.workspace = true
radio-core = { path = "../../crates/radio-core/" }
radio-db = { path = "../../crates/radio-db/", default-features = false }
radio-scanner = { path = "../../crates/radio-scanner/" }
serde_json = { version = "1.0.145" }
tokio.workspace = true
