[package]
name = "radio-db"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono = { version = "0.4.42", default-features = false, features = ["clock", "std"] }
diesel = { version = "2", default-features = false, optional = true }
diesel-async = { version = "0.7", default-features = false, optional = true }
libsqlite3-sys = { version = "0.37", features = ["bundled"], optional = true }
radio-core = { path = "../radio-core/" }

[features]
default = ["sqlite"]
sqlite = [
    "dep:diesel",
    "dep:diesel-async",
    "dep:libsqlite3-sys",
    "diesel/sqlite",
    "diesel/returning_clauses_for_sqlite_3_35",
    "diesel-async/sqlite",
]
postgres = [
    "dep:diesel",
    "dep:diesel-async",
    "diesel/postgres_backend",
    "diesel-async/postgres",
]

[dev-dependencies]
dotenvy.workspace = true
tokio.workspace = true
